/**
 * Curated city search seeds. Every `timezone` must be a real IANA id
 * (or a widely supported link such as Asia/Ho_Chi_Minh).
 * Multiple cities may share one timezone.
 */
export interface CityTimezoneSeed {
  timezone: string;
  city: string;
  country: string;
  countryCode: string;
  flag: string;
  aliases?: string[];
}

export const CITY_TIMEZONE_SEEDS: CityTimezoneSeed[] = [
  { timezone: "America/Toronto", city: "Toronto", country: "Canada", countryCode: "CA", flag: "🇨🇦", aliases: ["ontario", "est", "edt"] },
  { timezone: "America/Vancouver", city: "Vancouver", country: "Canada", countryCode: "CA", flag: "🇨🇦", aliases: ["bc", "pst", "pdt"] },
  { timezone: "America/Montreal", city: "Montreal", country: "Canada", countryCode: "CA", flag: "🇨🇦", aliases: ["québec", "quebec"] },
  { timezone: "America/Edmonton", city: "Edmonton", country: "Canada", countryCode: "CA", flag: "🇨🇦", aliases: ["calgary", "alberta"] },
  { timezone: "America/Edmonton", city: "Calgary", country: "Canada", countryCode: "CA", flag: "🇨🇦" },
  { timezone: "America/Winnipeg", city: "Winnipeg", country: "Canada", countryCode: "CA", flag: "🇨🇦" },
  { timezone: "America/Halifax", city: "Halifax", country: "Canada", countryCode: "CA", flag: "🇨🇦" },
  { timezone: "America/St_Johns", city: "St. John's", country: "Canada", countryCode: "CA", flag: "🇨🇦", aliases: ["newfoundland"] },
  { timezone: "America/New_York", city: "New York", country: "United States", countryCode: "US", flag: "🇺🇸", aliases: ["nyc", "usa", "est", "edt"] },
  { timezone: "America/New_York", city: "Washington", country: "United States", countryCode: "US", flag: "🇺🇸", aliases: ["dc", "washington dc"] },
  { timezone: "America/New_York", city: "Boston", country: "United States", countryCode: "US", flag: "🇺🇸" },
  { timezone: "America/New_York", city: "Philadelphia", country: "United States", countryCode: "US", flag: "🇺🇸" },
  { timezone: "America/New_York", city: "Miami", country: "United States", countryCode: "US", flag: "🇺🇸" },
  { timezone: "America/New_York", city: "Atlanta", country: "United States", countryCode: "US", flag: "🇺🇸" },
  { timezone: "America/Chicago", city: "Chicago", country: "United States", countryCode: "US", flag: "🇺🇸", aliases: ["cst", "cdt"] },
  { timezone: "America/Chicago", city: "Houston", country: "United States", countryCode: "US", flag: "🇺🇸" },
  { timezone: "America/Chicago", city: "Dallas", country: "United States", countryCode: "US", flag: "🇺🇸" },
  { timezone: "America/Chicago", city: "Minneapolis", country: "United States", countryCode: "US", flag: "🇺🇸" },
  { timezone: "America/Denver", city: "Denver", country: "United States", countryCode: "US", flag: "🇺🇸", aliases: ["mst", "mdt"] },
  { timezone: "America/Los_Angeles", city: "Los Angeles", country: "United States", countryCode: "US", flag: "🇺🇸", aliases: ["la", "pst", "pdt"] },
  { timezone: "America/Los_Angeles", city: "San Francisco", country: "United States", countryCode: "US", flag: "🇺🇸", aliases: ["sf", "bay area"] },
  { timezone: "America/Los_Angeles", city: "Seattle", country: "United States", countryCode: "US", flag: "🇺🇸" },
  { timezone: "America/Los_Angeles", city: "San Diego", country: "United States", countryCode: "US", flag: "🇺🇸" },
  { timezone: "America/Phoenix", city: "Phoenix", country: "United States", countryCode: "US", flag: "🇺🇸" },
  { timezone: "America/Detroit", city: "Detroit", country: "United States", countryCode: "US", flag: "🇺🇸" },
  { timezone: "America/Anchorage", city: "Anchorage", country: "United States", countryCode: "US", flag: "🇺🇸", aliases: ["alaska"] },
  { timezone: "Pacific/Honolulu", city: "Honolulu", country: "United States", countryCode: "US", flag: "🇺🇸", aliases: ["hawaii"] },
  { timezone: "America/Mexico_City", city: "Mexico City", country: "Mexico", countryCode: "MX", flag: "🇲🇽", aliases: ["cdmx"] },
  { timezone: "America/Cancun", city: "Cancún", country: "Mexico", countryCode: "MX", flag: "🇲🇽", aliases: ["cancun"] },
  { timezone: "America/Tijuana", city: "Tijuana", country: "Mexico", countryCode: "MX", flag: "🇲🇽" },
  { timezone: "America/Sao_Paulo", city: "São Paulo", country: "Brazil", countryCode: "BR", flag: "🇧🇷", aliases: ["sao paulo", "rio", "brasil"] },
  { timezone: "America/Buenos_Aires", city: "Buenos Aires", country: "Argentina", countryCode: "AR", flag: "🇦🇷" },
  { timezone: "America/Santiago", city: "Santiago", country: "Chile", countryCode: "CL", flag: "🇨🇱" },
  { timezone: "America/Bogota", city: "Bogotá", country: "Colombia", countryCode: "CO", flag: "🇨🇴", aliases: ["bogota"] },
  { timezone: "America/Lima", city: "Lima", country: "Peru", countryCode: "PE", flag: "🇵🇪" },
  { timezone: "America/Caracas", city: "Caracas", country: "Venezuela", countryCode: "VE", flag: "🇻🇪" },
  { timezone: "America/Panama", city: "Panama City", country: "Panama", countryCode: "PA", flag: "🇵🇦" },
  { timezone: "America/Costa_Rica", city: "San José", country: "Costa Rica", countryCode: "CR", flag: "🇨🇷" },
  { timezone: "America/Guatemala", city: "Guatemala City", country: "Guatemala", countryCode: "GT", flag: "🇬🇹" },
  { timezone: "America/Havana", city: "Havana", country: "Cuba", countryCode: "CU", flag: "🇨🇺" },
  { timezone: "America/Jamaica", city: "Kingston", country: "Jamaica", countryCode: "JM", flag: "🇯🇲" },
  { timezone: "America/Puerto_Rico", city: "San Juan", country: "Puerto Rico", countryCode: "PR", flag: "🇵🇷" },

  { timezone: "Europe/London", city: "London", country: "United Kingdom", countryCode: "GB", flag: "🇬🇧", aliases: ["uk", "england", "gmt", "bst"] },
  { timezone: "Europe/London", city: "Manchester", country: "United Kingdom", countryCode: "GB", flag: "🇬🇧" },
  { timezone: "Europe/London", city: "Edinburgh", country: "United Kingdom", countryCode: "GB", flag: "🇬🇧" },
  { timezone: "Europe/Dublin", city: "Dublin", country: "Ireland", countryCode: "IE", flag: "🇮🇪" },
  { timezone: "Europe/Paris", city: "Paris", country: "France", countryCode: "FR", flag: "🇫🇷", aliases: ["france", "lyon", "marseille", "cet", "cest"] },
  { timezone: "Europe/Paris", city: "Lyon", country: "France", countryCode: "FR", flag: "🇫🇷" },
  { timezone: "Europe/Berlin", city: "Berlin", country: "Germany", countryCode: "DE", flag: "🇩🇪", aliases: ["germany", "munich", "frankfurt"] },
  { timezone: "Europe/Berlin", city: "Munich", country: "Germany", countryCode: "DE", flag: "🇩🇪", aliases: ["münchen"] },
  { timezone: "Europe/Amsterdam", city: "Amsterdam", country: "Netherlands", countryCode: "NL", flag: "🇳🇱", aliases: ["holland"] },
  { timezone: "Europe/Brussels", city: "Brussels", country: "Belgium", countryCode: "BE", flag: "🇧🇪" },
  { timezone: "Europe/Madrid", city: "Madrid", country: "Spain", countryCode: "ES", flag: "🇪🇸", aliases: ["barcelona"] },
  { timezone: "Europe/Madrid", city: "Barcelona", country: "Spain", countryCode: "ES", flag: "🇪🇸" },
  { timezone: "Europe/Lisbon", city: "Lisbon", country: "Portugal", countryCode: "PT", flag: "🇵🇹" },
  { timezone: "Europe/Rome", city: "Rome", country: "Italy", countryCode: "IT", flag: "🇮🇹", aliases: ["milan", "milano"] },
  { timezone: "Europe/Rome", city: "Milan", country: "Italy", countryCode: "IT", flag: "🇮🇹" },
  { timezone: "Europe/Zurich", city: "Zurich", country: "Switzerland", countryCode: "CH", flag: "🇨🇭", aliases: ["geneva"] },
  { timezone: "Europe/Vienna", city: "Vienna", country: "Austria", countryCode: "AT", flag: "🇦🇹" },
  { timezone: "Europe/Stockholm", city: "Stockholm", country: "Sweden", countryCode: "SE", flag: "🇸🇪" },
  { timezone: "Europe/Oslo", city: "Oslo", country: "Norway", countryCode: "NO", flag: "🇳🇴" },
  { timezone: "Europe/Copenhagen", city: "Copenhagen", country: "Denmark", countryCode: "DK", flag: "🇩🇰" },
  { timezone: "Europe/Helsinki", city: "Helsinki", country: "Finland", countryCode: "FI", flag: "🇫🇮" },
  { timezone: "Europe/Warsaw", city: "Warsaw", country: "Poland", countryCode: "PL", flag: "🇵🇱" },
  { timezone: "Europe/Prague", city: "Prague", country: "Czech Republic", countryCode: "CZ", flag: "🇨🇿" },
  { timezone: "Europe/Budapest", city: "Budapest", country: "Hungary", countryCode: "HU", flag: "🇭🇺" },
  { timezone: "Europe/Bucharest", city: "Bucharest", country: "Romania", countryCode: "RO", flag: "🇷🇴" },
  { timezone: "Europe/Athens", city: "Athens", country: "Greece", countryCode: "GR", flag: "🇬🇷" },
  { timezone: "Europe/Istanbul", city: "Istanbul", country: "Turkey", countryCode: "TR", flag: "🇹🇷" },
  { timezone: "Europe/Moscow", city: "Moscow", country: "Russia", countryCode: "RU", flag: "🇷🇺" },
  { timezone: "Europe/Kyiv", city: "Kyiv", country: "Ukraine", countryCode: "UA", flag: "🇺🇦", aliases: ["kiev"] },
  { timezone: "Europe/Belgrade", city: "Belgrade", country: "Serbia", countryCode: "RS", flag: "🇷🇸" },
  { timezone: "Europe/Sofia", city: "Sofia", country: "Bulgaria", countryCode: "BG", flag: "🇧🇬" },
  { timezone: "Atlantic/Reykjavik", city: "Reykjavik", country: "Iceland", countryCode: "IS", flag: "🇮🇸" },

  // Vietnam: prefer Ho_Chi_Minh; Saigon is a common link id in some runtimes
  { timezone: "Asia/Ho_Chi_Minh", city: "Ho Chi Minh City", country: "Vietnam", countryCode: "VN", flag: "🇻🇳", aliases: ["vietnam", "saigon", "hcmc", "asia/saigon", "ict", "viet nam"] },
  { timezone: "Asia/Ho_Chi_Minh", city: "Hanoi", country: "Vietnam", countryCode: "VN", flag: "🇻🇳", aliases: ["ha noi", "vietnam"] },
  { timezone: "Asia/Ho_Chi_Minh", city: "Da Nang", country: "Vietnam", countryCode: "VN", flag: "🇻🇳", aliases: ["danang"] },
  { timezone: "Asia/Bangkok", city: "Bangkok", country: "Thailand", countryCode: "TH", flag: "🇹🇭" },
  { timezone: "Asia/Phnom_Penh", city: "Phnom Penh", country: "Cambodia", countryCode: "KH", flag: "🇰🇭" },
  { timezone: "Asia/Vientiane", city: "Vientiane", country: "Laos", countryCode: "LA", flag: "🇱🇦" },
  { timezone: "Asia/Yangon", city: "Yangon", country: "Myanmar", countryCode: "MM", flag: "🇲🇲", aliases: ["rangoon"] },
  { timezone: "Asia/Jakarta", city: "Jakarta", country: "Indonesia", countryCode: "ID", flag: "🇮🇩", aliases: ["bali", "denpasar"] },
  { timezone: "Asia/Makassar", city: "Makassar", country: "Indonesia", countryCode: "ID", flag: "🇮🇩" },
  { timezone: "Asia/Singapore", city: "Singapore", country: "Singapore", countryCode: "SG", flag: "🇸🇬" },
  { timezone: "Asia/Kuala_Lumpur", city: "Kuala Lumpur", country: "Malaysia", countryCode: "MY", flag: "🇲🇾", aliases: ["kl"] },
  { timezone: "Asia/Manila", city: "Manila", country: "Philippines", countryCode: "PH", flag: "🇵🇭" },
  { timezone: "Asia/Hong_Kong", city: "Hong Kong", country: "Hong Kong", countryCode: "HK", flag: "🇭🇰" },
  { timezone: "Asia/Macau", city: "Macau", country: "Macau", countryCode: "MO", flag: "🇲🇴" },
  { timezone: "Asia/Taipei", city: "Taipei", country: "Taiwan", countryCode: "TW", flag: "🇹🇼" },
  { timezone: "Asia/Shanghai", city: "Shanghai", country: "China", countryCode: "CN", flag: "🇨🇳", aliases: ["beijing", "china", "guangzhou", "shenzhen"] },
  { timezone: "Asia/Shanghai", city: "Beijing", country: "China", countryCode: "CN", flag: "🇨🇳" },
  { timezone: "Asia/Shanghai", city: "Guangzhou", country: "China", countryCode: "CN", flag: "🇨🇳" },
  { timezone: "Asia/Shanghai", city: "Shenzhen", country: "China", countryCode: "CN", flag: "🇨🇳" },
  { timezone: "Asia/Tokyo", city: "Tokyo", country: "Japan", countryCode: "JP", flag: "🇯🇵", aliases: ["japan", "jst", "osaka"] },
  { timezone: "Asia/Tokyo", city: "Osaka", country: "Japan", countryCode: "JP", flag: "🇯🇵" },
  { timezone: "Asia/Seoul", city: "Seoul", country: "South Korea", countryCode: "KR", flag: "🇰🇷", aliases: ["korea"] },
  { timezone: "Asia/Pyongyang", city: "Pyongyang", country: "North Korea", countryCode: "KP", flag: "🇰🇵" },
  { timezone: "Asia/Kolkata", city: "Mumbai", country: "India", countryCode: "IN", flag: "🇮🇳", aliases: ["bombay", "india", "ist"] },
  { timezone: "Asia/Kolkata", city: "New Delhi", country: "India", countryCode: "IN", flag: "🇮🇳", aliases: ["delhi"] },
  { timezone: "Asia/Kolkata", city: "Bengaluru", country: "India", countryCode: "IN", flag: "🇮🇳", aliases: ["bangalore"] },
  { timezone: "Asia/Kolkata", city: "Chennai", country: "India", countryCode: "IN", flag: "🇮🇳" },
  { timezone: "Asia/Kolkata", city: "Hyderabad", country: "India", countryCode: "IN", flag: "🇮🇳" },
  { timezone: "Asia/Kathmandu", city: "Kathmandu", country: "Nepal", countryCode: "NP", flag: "🇳🇵" },
  { timezone: "Asia/Dhaka", city: "Dhaka", country: "Bangladesh", countryCode: "BD", flag: "🇧🇩" },
  { timezone: "Asia/Karachi", city: "Karachi", country: "Pakistan", countryCode: "PK", flag: "🇵🇰", aliases: ["islamabad"] },
  { timezone: "Asia/Colombo", city: "Colombo", country: "Sri Lanka", countryCode: "LK", flag: "🇱🇰" },
  { timezone: "Asia/Dubai", city: "Dubai", country: "United Arab Emirates", countryCode: "AE", flag: "🇦🇪", aliases: ["uae", "abu dhabi"] },
  { timezone: "Asia/Dubai", city: "Abu Dhabi", country: "United Arab Emirates", countryCode: "AE", flag: "🇦🇪" },
  { timezone: "Asia/Riyadh", city: "Riyadh", country: "Saudi Arabia", countryCode: "SA", flag: "🇸🇦" },
  { timezone: "Asia/Qatar", city: "Doha", country: "Qatar", countryCode: "QA", flag: "🇶🇦" },
  { timezone: "Asia/Kuwait", city: "Kuwait City", country: "Kuwait", countryCode: "KW", flag: "🇰🇼" },
  { timezone: "Asia/Bahrain", city: "Manama", country: "Bahrain", countryCode: "BH", flag: "🇧🇭" },
  { timezone: "Asia/Jerusalem", city: "Jerusalem", country: "Israel", countryCode: "IL", flag: "🇮🇱" },
  { timezone: "Asia/Jerusalem", city: "Tel Aviv", country: "Israel", countryCode: "IL", flag: "🇮🇱" },
  { timezone: "Asia/Beirut", city: "Beirut", country: "Lebanon", countryCode: "LB", flag: "🇱🇧" },
  { timezone: "Asia/Amman", city: "Amman", country: "Jordan", countryCode: "JO", flag: "🇯🇴" },
  { timezone: "Asia/Baghdad", city: "Baghdad", country: "Iraq", countryCode: "IQ", flag: "🇮🇶" },
  { timezone: "Asia/Tehran", city: "Tehran", country: "Iran", countryCode: "IR", flag: "🇮🇷" },
  { timezone: "Asia/Tbilisi", city: "Tbilisi", country: "Georgia", countryCode: "GE", flag: "🇬🇪" },
  { timezone: "Asia/Yerevan", city: "Yerevan", country: "Armenia", countryCode: "AM", flag: "🇦🇲" },
  { timezone: "Asia/Baku", city: "Baku", country: "Azerbaijan", countryCode: "AZ", flag: "🇦🇿" },
  { timezone: "Asia/Almaty", city: "Almaty", country: "Kazakhstan", countryCode: "KZ", flag: "🇰🇿" },
  { timezone: "Asia/Tashkent", city: "Tashkent", country: "Uzbekistan", countryCode: "UZ", flag: "🇺🇿" },
  { timezone: "Asia/Ulaanbaatar", city: "Ulaanbaatar", country: "Mongolia", countryCode: "MN", flag: "🇲🇳" },

  { timezone: "Australia/Sydney", city: "Sydney", country: "Australia", countryCode: "AU", flag: "🇦🇺", aliases: ["aest", "aedt", "canberra"] },
  { timezone: "Australia/Melbourne", city: "Melbourne", country: "Australia", countryCode: "AU", flag: "🇦🇺" },
  { timezone: "Australia/Brisbane", city: "Brisbane", country: "Australia", countryCode: "AU", flag: "🇦🇺" },
  { timezone: "Australia/Perth", city: "Perth", country: "Australia", countryCode: "AU", flag: "🇦🇺" },
  { timezone: "Australia/Adelaide", city: "Adelaide", country: "Australia", countryCode: "AU", flag: "🇦🇺" },
  { timezone: "Pacific/Auckland", city: "Auckland", country: "New Zealand", countryCode: "NZ", flag: "🇳🇿" },
  { timezone: "Pacific/Auckland", city: "Wellington", country: "New Zealand", countryCode: "NZ", flag: "🇳🇿" },
  { timezone: "Pacific/Fiji", city: "Suva", country: "Fiji", countryCode: "FJ", flag: "🇫🇯" },
  { timezone: "Pacific/Guam", city: "Guam", country: "Guam", countryCode: "GU", flag: "🇬🇺" },
  { timezone: "Pacific/Tahiti", city: "Papeete", country: "French Polynesia", countryCode: "PF", flag: "🇵🇫", aliases: ["tahiti"] },

  { timezone: "Africa/Cairo", city: "Cairo", country: "Egypt", countryCode: "EG", flag: "🇪🇬" },
  { timezone: "Africa/Johannesburg", city: "Johannesburg", country: "South Africa", countryCode: "ZA", flag: "🇿🇦" },
  { timezone: "Africa/Johannesburg", city: "Cape Town", country: "South Africa", countryCode: "ZA", flag: "🇿🇦" },
  { timezone: "Africa/Lagos", city: "Lagos", country: "Nigeria", countryCode: "NG", flag: "🇳🇬" },
  { timezone: "Africa/Nairobi", city: "Nairobi", country: "Kenya", countryCode: "KE", flag: "🇰🇪" },
  { timezone: "Africa/Casablanca", city: "Casablanca", country: "Morocco", countryCode: "MA", flag: "🇲🇦" },
  { timezone: "Africa/Accra", city: "Accra", country: "Ghana", countryCode: "GH", flag: "🇬🇭" },
  { timezone: "Africa/Addis_Ababa", city: "Addis Ababa", country: "Ethiopia", countryCode: "ET", flag: "🇪🇹" },
  { timezone: "Africa/Dar_es_Salaam", city: "Dar es Salaam", country: "Tanzania", countryCode: "TZ", flag: "🇹🇿" },
  { timezone: "Africa/Algiers", city: "Algiers", country: "Algeria", countryCode: "DZ", flag: "🇩🇿" },
  { timezone: "Africa/Tunis", city: "Tunis", country: "Tunisia", countryCode: "TN", flag: "🇹🇳" },

  { timezone: "UTC", city: "UTC", country: "Worldwide", countryCode: "UN", flag: "🌐", aliases: ["gmt", "zulu", "universal"] },
];
